### ISSUE TITLE
Barrel recipe overrides all Minecraft barrel recipes. Ref.Ex. SpoornPink

### ISSUE THREAD

**Issue by Neonis00** [spoorn/SpoornPacks#2]
Version: "spoornpacks-4.2-1.18.2"
--> "spoornpink-3.3"

When using SpoornPink, the barrel recipe is overriding all barrel recipes, causing every wood type to craft Pink Blossom Barrel.

Reference issue:
https://github.com/spoorn/SpoornPink/issues/4#issue-1198863091

Example images:
![image](https://user-images.githubusercontent.com/47197231/162600837-3f199c5d-076a-4e20-b21d-cd002c3840a8.png)

**Comment by spoorn** [comment]
See updates and any continuing correspondence on https://github.com/spoorn/SpoornPink/issues/4
