### ISSUE TITLE
Spoorn 1.18.2 

### ISSUE THREAD

**Issue by Balakay420** [spoorn/SpoornPacks#3]
When I’m create a world it says spoornpack is incompatible and is made for an older version of Minecraft. I cant load a world due to this

**Comment by spoorn** [comment]
Do you have a log?

**Comment by Balakay420** [comment]
![Screenshot 2022-06-03 051131](https://user-images.githubusercontent.com/106470691/171835227-bb80e2b8-2287-4387-8179-99e1f0e1e783.png)
I dont but it looks like this. Latest version of fabric and latest version of fabric api

**Comment by Balakay420** [comment]
![image](https://user-images.githubusercontent.com/106470691/171835403-013dcdd7-0e48-4482-b755-77446418ef57.png)
when hovering over it

**Comment by spoorn** [comment]
what version of SpoornPacks are you using, and what versions of Fabric/Minecraft

**Comment by Balakay420** [comment]
Minecraft- 1.18.2
fabric api- 0.54.0+1.18.2
Mod version- 4.2.1-1.18.2

**Comment by Balakay420** [comment]
Fabric 0.14.6

**Comment by spoorn** [comment]
I believe that's just the message on the resource packs screen, but it'd still work.  I probably just need to update to the latest versions of everything, but it's the same version of minecraft 1.18.2, so it works.

I won't bother updating for 1.18.2 anymore though as 1.19 is out now
