### ISSUE TITLE
Error validating datapacks when creating world

### ISSUE THREAD

**Issue by Balakay420** [spoorn/SpoornPacks#7]
I try to create a world and it says unable to validate datapacks. The autogenerated pack spoornpacks is red and says "this was made for an older version of Minecraft"

**Comment by spoorn** [comment]
Do you have logs?  Which version of minecraft, Fabric, Fabric Loader, and Spoornpacks?

**Comment by Balakay420** [comment]
1.18.2 Minecraft 
0.14.8 fabric loader
0.56.1 fabric api
4.2.2 SpoornPacks

**Comment by spoorn** [comment]
Do you have a log that shows the message, or screenshot?  And what other mods do you have, or modpack are you using?  I can't reproduce this on my end

**Comment by Balakay420** [comment]
Ill send screenshot and check logs when I get home later, it started after I installed dimensional doors.

**Comment by Balakay420** [comment]
Try it with that

I was having the same validation error with that mod so I went into their .jar and edited the pack.mcmeta pack_format: to 9 for 1.18.2 and it fixed it for their mod.

Your mod generates the resource pack dynamically if I'm not mistaken, right?

**Comment by spoorn** [comment]
Yes, and it generates the pack.mcmeta dynamically as well using the latest version for the game version: https://github.com/spoorn/SpoornPacks/blob/1.18/src/main/java/org/spoorn/spoornpacks/core/SPGroupResourcePack.java#L28

I'm using the same versions as you as well and don't see any problems, so I wonder if it's conflicting with another mod

**Comment by Balakay420** [comment]
Install with https://www.curseforge.com/minecraft/mc-mods/dimensionaldoors/files/3732839 

4.0.4-1.18.2

**Comment by spoorn** [comment]
Yeah, I was able to run with both on my modpack which has a ton of other mods too: https://www.curseforge.com/minecraft/modpacks/spoornpack-fabric

Could you send me a full list of your mods, and/or a log file?  If you want, you could also ping me in my discord server

**Comment by Balakay420** [comment]
https://paste.ee/p/VKTK6

**Comment by Balakay420** [comment]
Architects palette was the problem mod, sorry lol. thanks for the help!!
