### ISSUE TITLE
Crash during startup on 1.19.2?

### ISSUE THREAD

**Issue by WimpieRatte** [spoorn/SpoornPacks#8]
Fabric loader 0.14.21.

When starting up with this mod (SpoornPacks), it crashes during startup. 
Here's the full Mincraft Log:

https://github.com/WimpieRatte/SharedFiles/blob/main/20230601MinecraftCrash

**Comment by aninusmuffin** [comment]
You are using the 1.19.3 version of the mod (spoornpacks-4.4-1.19.3)
For some reason the 1.19.3 versions of SpoornPacks and myloot mods are marked as 1.19-1.19.3 on modrinth.

**Comment by WimpieRatte** [comment]
Yeah, it's from Modrinth that I'm getting the mods from.

**Comment by spoorn** [comment]
Sorry, I fixed this on Modrinth
